name: Validate Migrations

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/migrations/**

jobs:
  validate_migrations:
    name: Validate Migrations
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: validate migrations
        run: node backend/scripts/check_duplicate_migrations.js
    